export const GET_SONGS = "GET_SONGS"
export const GET_SONGS_SUCCESS = "GET_SONGS_SUCCESS"
export const GET_MOVIES = "GET_MOVIES"
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS"
export const ADD_MOVIE = "ADD_MOVIE"
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS"
export const GET_PROFILE = "GET_PROFILE"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"

export const GET_FAVORITE_SINGERS = "GET_FAVORITE_SINGERS"
export const GET_FAVORITE_ACTORS = "GET_FAVORITE_ACTORS"

export const GET_FAVORITE_SINGERS_SUCCESS = "GET_FAVORITE_SINGERS_SUCCESS"
export const GET_FAVORITE_ACTORS_SUCCESS = "GET_FAVORITE_ACTORS_SUCCESS"



